# -*- coding: utf-8 -*-
"""project 110

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xDDwE3WJ5S7n7Q-ZpjVKYsESztND5b8_
"""

from google.colab import files
data_to_load = files.upload()

import statistics
import csv
import pandas as pd
import random
import plotly.figure_factory as ff
import plotly.graph_objects as go

df = pd.read_csv("medium_data.csv")
data = df["claps"].tolist()

meanClaps = statistics.mean(data)
standardDev = statistics.stdev(data)

firstStandardDeviationStart, firstStandardDeviationEnd = meanClaps - standardDev, meanClaps + standardDev
secondStandardDeviationStart, secondStandardDeviationEnd = meanClaps -(2 * standardDev), meanClaps + (2* standardDev)
thirdStandardDeviationStart, thirdStandardDeviationEnd = meanClaps -(3 * standardDev), meanClaps + (3* standardDev)



print(meanClaps)

def takeData(counter):
  dataset = []
  for i in range(0, counter):
    random_index = random.randint(0, len(data)-1)
    value = data[random_index]
    dataset.append(value)
  mean = statistics.mean(dataset)
  return mean


def repeat():
  meanList=[]
  for i in range(0,100):
    set_of_means = takeData(30)
    meanList.append(set_of_means)
  show_fig(meanList)
  return meanList


def show_fig(meanList):

    fig = ff.create_distplot([meanList], ["claps"], show_hist = False)
    fig.add_trace(go.Scatter(x= [firstStandardDeviationEnd, firstStandardDeviationEnd], y = [0,0.17], mode = "lines", name = "first standard deviation end"))
    fig.add_trace(go.Scatter(x= [secondStandardDeviationEnd, secondStandardDeviationEnd], y = [0,0.17], mode = "lines", name = "second standard deviation end"))
    fig.add_trace(go.Scatter(x= [thirdStandardDeviationEnd, thirdStandardDeviationEnd], y = [0,0.17], mode = "lines", name = "third standard deviation end"))
    fig.add_trace(go.Scatter(x= [meanClaps, meanClaps], y = [0,0.17], mode = "lines", name = "mean"))
    fig.show()


lists  = repeat()
show_fig(lists)
newMean = statistics.mean(lists)

print("zcore" + (newMena - meanClaps)/standardDev)


print()

